#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    vicompatible = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "sonokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_iseparator = "slant"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    filemanager = 'defx'
    autocomplete_method = 'coc'
    bootstrap_before = 'blood#before'
    bootstrap_after = 'blood#after'
    default_indent = 4

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 50

[[layers]]
    name = 'checkers'

[[layers]]
    name = 'VersionControl'

[[layers]]
    name = 'git'
    git-plugin = 'fugitive'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'lang#python'
    python_file_head = []

[[layers]]
    name = 'lang#html'

[[layers]]
    name = 'lang#javascript'

[[layers]]
    name = 'lang#vue'

[[layers]]
    name = 'lang#toml'

[[custom_plugins]]
    repo = 'sainnhe/sonokai'
    merged = false

[[custom_plugins]]
    repo = 'kristijanhusak/defx-icons'
    merged = false

[[custom_plugins]]
    repo = 'kristijanhusak/defx-git'
    merged = false

[[custom_plugins]]
    repo = 'cheap-glitch/vim-v'
    merged = false

[[custom_plugins]]
    repo = 'skanehira/preview-markdown.vim'
    merged = false
